# Generated by Django 3.0.2 on 2020-02-21 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('macau_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='macau_game.Game'),
        ),
        migrations.AlterField(
            model_name='card',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='move',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='macau_game.Game'),
        ),
        migrations.AlterField(
            model_name='move',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='throw',
            name='move',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='macau_game.Move'),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.SmallIntegerField()),
                ('done', models.BooleanField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='macau_game.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
