# Generated by Django 3.0.2 on 2020-02-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macau_game', '0002_auto_20200221_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='full',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
